import { Adoption } from './../../tsModels/adoption.model';
interface AdoptionCollection extends Array<Adoption> {}
export const gatosExample:AdoptionCollection = [
    {  _id : 'cat01',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'gato',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/L0C8D.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : 'cat02',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'gato',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/L0C8D.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : 'cat03',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'gato',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/L0C8D.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : 'cat04',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'gato',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/L0C8D.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : 'cat05',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'gato',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/L0C8D.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : 'cat06',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'gato',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/L0C8D.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  }
]