import { Adoption } from './../../tsModels/adoption.model';
interface AdoptionCollection extends Array<Adoption> {}
export const perrosExample:AdoptionCollection = [
    {  _id : '1',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/C5ZpUTu.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : '2',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/C5ZpUTu.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : '3',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/C5ZpUTu.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : '4',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/C5ZpUTu.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : '5',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/C5ZpUTu.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : '6',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'cuca',
      agePet:3,
      genderPet:'hembra',
      imagenPet:'https://i.imgur.com/C5ZpUTu.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  }
]