import { Adoption } from "./../../tsModels/adoption.model";
interface AdoptionCollection extends Array<Adoption> {}
export const perrosExample: AdoptionCollection = [
  {
    _id: "dog06",
    fechaCreacion: "2023-07-22T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Cucquita",
    agePet: 3,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/QdYf3Hb9/Cuquita.jpg",
    fechaRecoleccion: new Date("2021-01-15T06:00:00.000+00:00"),
    sizePet: "Mediana",
    energyPet: "Media",
    description:
      "Fue rescatada cuando vecinos alertaron que un perrito había sido atacado por un arma de fuego.",
    convive: false,
    descriptionConvive: "Convive con otros perritos, cachorros y adultos.",
  },
  {
    _id: "dog02",
    fechaCreacion: "2023-07-08T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Lottie",
    agePet: 1,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/pd4f5snc/Lottie.jpg",
    fechaRecoleccion: new Date("2022-01-15T06:00:00.000+00:00"),
    sizePet: "Mediana",
    energyPet: "Media",
    description:
      "Fue rescatada junto a sus 4 hermanos a los 15 días, su mamá fue envenenada.",
    convive: false,
    descriptionConvive: "Convive con otros perritos, cachorros y adultos.",
  },
  {
    _id: "dog04",
    fechaCreacion: "2023-07-08T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Mila",
    agePet: 10,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/xCLzJnQq/Mila.jpg",
    fechaRecoleccion: new Date("2022-06-01T06:00:00.000+00:00"),
    sizePet: "Grande",
    energyPet: "Baja",
    description:
      "Fue rescatada en estado de gestación avanzada y sobreviviente de TVT.",
    convive: true,
    descriptionConvive:
      "Convive con otros perritos, cachorros y adultos y gatos.",
  },
  {
    _id: "dog08",
    fechaCreacion: "2023-07-22T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Tasha",
    agePet: 3,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/TwVjpwrc/Tasha.jpg",
    fechaRecoleccion: new Date("2022-07-15T06:00:00.000+00:00"),
    sizePet: "Mediana",
    energyPet: "Media-Alta",
    description:
      "Fue rescatada en estado de gestación avanzada, sobreviviente de TVT y parvovirus.",
    convive: false,
    descriptionConvive: "No convive con perros ni gatos.",
  },
  {
    _id: "dog07",
    fechaCreacion: "2023-07-22T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Berni",
    agePet: 4,
    genderPet: "Macho",
    imagenPet: "https://i.postimg.cc/MpLmLg61/Berni.jpg",
    fechaRecoleccion: new Date("2023-01-15T06:00:00.000+00:00"),
    sizePet: "Grande",
    energyPet: "Media-Alta",
    description: "fue rescatado en el canal de San Bernardino.",
    convive: true,
    descriptionConvive:
      "Convive con otros perritos, cachorros y adultos y gatos.",
  },
  {
    _id: "dog01",
    fechaCreacion: "2023-07-08T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Kimichi",
    agePet: 0.4,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/x8r3h6fN/Lili-OKimechi.jpg",
    fechaRecoleccion: new Date("2023-03-06T06:00:00.000+00:00"),
    sizePet: "Mediana",
    energyPet: "Media",
    description:
      "Fue rescatada cuandoa las pocas horas de nacida fue tirada en una bolsa de basura junto con sus 7 hermanos, es la única sobreviviente.",
    convive: true,
    descriptionConvive:
      "Convive con otros perritos, cachorros y adultos y gatos.",
  },

  {
    _id: "dog03",
    fechaCreacion: "2023-05-03T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Shensy",
    agePet: 0.5,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/15BDrmqq/Shensy.jpg",
    fechaRecoleccion: new Date("2023-05-15T06:00:00.000+00:00"),
    sizePet: "Mediana",
    energyPet: "Media",
    description:
      "Fue encontrada a mitad de la calle y es sobreviviente de parvovirus. ",
    convive: false,
    descriptionConvive: "Convive con otros perritos, cachorros y adultos.",
  },

  {
    _id: "dog09",
    fechaCreacion: "2023-07-22T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Susie",
    agePet: 0.5,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/vHH7ZGDW/Susie.jpg",
    fechaRecoleccion: new Date("2023-05-15T06:00:00.000+00:00"),
    sizePet: "Chica",
    energyPet: "Baja",
    description:
      "Rescatada junto con sus hermanitas en un caja, sus dueños solo se quedaron el macho.",
    convive: false,
    descriptionConvive: "Convive con otros perritos.",
  },
  {
    _id: "dog10",
    fechaCreacion: "2023-07-22T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Kimi",
    agePet: 0.5,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/y820j9jP/Kimi.jpg",
    fechaRecoleccion: new Date("2023-05-15T06:00:00.000+00:00"),
    sizePet: "Chica",
    energyPet: "Media",
    description:
      "Rescatada junto con sus hermanitas en un caja, sus dueños solo se quedaron el macho.",
    convive: false,
    descriptionConvive: "Convive con otros perritos.",
  },
  {
    _id: "dog11",
    fechaCreacion: "2023-07-22T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Angélica",
    agePet: 0.5,
    genderPet: "Hembra",
    imagenPet: "https://i.postimg.cc/JzHks08B/angelica.jpg",
    fechaRecoleccion: new Date("2023-05-15T06:00:00.000+00:00"),
    sizePet: "Chica",
    energyPet: "Media",
    description:
      "Rescatada junto con sus hermanitas en un caja, sus dueños solo se quedaron el macho.",
    convive: false,
    descriptionConvive: "Convive con otros perritos.",
  },
  {
    _id: "dog05",
    fechaCreacion: "2023-07-08T06:00:00.000+00:00",
    collection: "perro",
    namePet: "Frankie",
    agePet: 1,
    genderPet: "Macho",
    imagenPet: "https://i.postimg.cc/k5BZdhmT/Frankie.jpg",
    fechaRecoleccion: new Date("2023-07-10T06:00:00.000+00:00"),
    sizePet: "Grande",
    energyPet: "Media",
    description:
      "Fue rescatado con fractura distal de húmero y se encuentra en proceso de rehabilitación.",
    convive: true,
    descriptionConvive:
      "Convive con otros perritos, cachorros y adultos y gatos.",
  },
];
