import { Adoption } from './../../tsModels/adoption.model';
interface AdoptionCollection extends Array<Adoption> {}
export const perrosExample:AdoptionCollection = [
    {  _id : 'dog01',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'Kimichi',
      agePet:0.4,
      genderPet:'Hembra',
      imagenPet:'https://i.postimg.cc/x8r3h6fN/Lili-OKimechi.jpg',
      fechaRecoleccion:new Date('2023-03-06T06:00:00.000+00:00'),
      sizePet:'Grande',
      energyPet:'Media',
      description:'fue arrojada en una bolsa  de plástico junto a sus 7 hermanos enseguida que nació, 3 hermanitos se fueron con una mamá nodriza, 4 se quedaron con su rescatista, ella es la unica sobreviviente de esos 4 bebés'
  },
  {  _id : 'dog02',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'Lottie',
      agePet:1,
      genderPet:'Hembra',
      imagenPet:'https://i.postimg.cc/pd4f5snc/Lottie.jpg',
      fechaRecoleccion:new Date('2022-01-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Alta',
      description:'fue rescatada a los 15 días con sus 4 hermanos, sin su mamita.Ha tenido dos adoptantes, una nos la regresó y la otra nosotros la retiramos por que la tenian amarrada todo el tiempo'
  },
  {  _id : 'dog03',
      fechaCreacion: '2023-05-03T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'Shensy',
      agePet:0.5,
      genderPet:'Hembra',
      imagenPet:'https://i.postimg.cc/15BDrmqq/Shensy.jpg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana-Grande',
      energyPet:'Media',
      description:'Se entrega vacunada, desparasitada y vacunada.'
  },
  {  _id : 'dog04',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'Mila',
      agePet:1,
      genderPet:'Hembra',
      imagenPet:'https://i.postimg.cc/xCLzJnQq/Mila.jpg',
      fechaRecoleccion:new Date('2022-06-01T06:00:00.000+00:00'),
      sizePet:'Mediana-Grande',
      energyPet:'Media',
      description:'Super amoroso. En proceso de rehabilitación por fractura de húmero.  Se entrega vacunado, desparasitado, esterilizado.'
  },
  {  _id : 'dog05',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'Frankie',
      agePet:3,
      genderPet:'Macho',
      imagenPet:'https://i.postimg.cc/k5BZdhmT/Frankie.jpg',
      fechaRecoleccion:new Date('2023-07-10T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  },
  {  _id : 'dog06',
      fechaCreacion: '2023-07-08T06:00:00.000+00:00',
      collection: 'perro',
      namePet:'cuca',
      agePet:3,
      genderPet:'Hembra',
      imagenPet:'https://i.imgur.com/C5ZpUTu.jpeg',
      fechaRecoleccion:new Date('2023-05-15T06:00:00.000+00:00'),
      sizePet:'Mediana',
      energyPet:'Media',
      description:'Fui rescatada por Brigada Murci en enero 2021 después que un vecino de la comunidad reporto que fui atacada con un arma de fuego directo a la cara.'
  }
]