//Fuente
import { Poppins } from "next/font/google";
//Components
import Head from "next/head";
import ClientOnly from "@/components/ClientOnly/ClientOnly";
import HeaderPage from "@/components/HeaderPage/HeaderPage";
import CardPDP from "@/components/CardPDP/CardPDP";
import ButtonsPDP from "@/components/ButtonsPDP/ButtonsPDP";
import Footer from "@/components/Footer/Footer";
//Hooks
import useDevice from "@/hooks/useDevice";
//DATABASE
import {perrosExample} from '../../database/examples/perrosExample'
import { gatosExample } from "../../database/examples/gatosExample";
//Models
import DeviceUnvailable from "@/components/DeviceUnvailable/DeviceUnvailable";
import { GetServerSideProps } from "next";
interface PdpMascotaProps {
  data: any
}

const popins = Poppins({weight:['500','100','900'],subsets:["latin"],variable:'--font-popins'});

const PdpMAscota:React.FC<PdpMascotaProps> =({data}) => {
  const { device } = useDevice();
    const datos = JSON.parse(data)
    //console.log(4,datos)
    //Collection
    const collectionPet = datos?.collection
    //Images
    const imagenPet01 = datos?.imagenPet
    //Name and Gender
    const namePet = datos?.namePet
    const genderPet = datos?.genderPet
    //Dias de espera
    const diaQueLlego = datos?.fechaRecoleccion
    //Stats
    const energyPet = datos?.energyPet
    const sizePet = datos?.sizePet
    const agePet = datos?.agePet
    //Description
    const desctiptionPet00 = datos?.description
    const convive = datos?.convive
    const descriptionPet01 =datos?.descriptionConvive

    return (
      <>
        <Head>
          <title>Brigada Murci Adoptables</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/BrigadaMurciLogoV.png" />
        </Head>
        <ClientOnly>
        <body className={`${popins.variable}`}>
          <DeviceUnvailable device={device}/>
          <HeaderPage device={device} collection={collectionPet}/>
          <CardPDP device={device} imagen01={imagenPet01} namePet={namePet} genderPet={genderPet} diaQueLlego={diaQueLlego} energyPet={energyPet} sizePet={sizePet} agePet={agePet} description00={desctiptionPet00} convive={convive} descriptionConvive={descriptionPet01}/>
          <ButtonsPDP device={device}/>
          <Footer device={device}/>
        </body>
        </ClientOnly>
      </>
    );
}

export default PdpMAscota

export const getServerSideProps: GetServerSideProps = async (context) => {
  const IdPage = context?.query?.pdpMascota;
  //console.log(IdPage)

  const res01 = perrosExample.find(el => el._id === IdPage)
  //console.log(1 ,res01)
  const res02 = gatosExample.find(el => el._id === IdPage)
  //console.log(2 ,res02)
  let previewData 
  res01 === undefined && res02 === undefined ? previewData = null : previewData = res01
   //res01 === undefined ? previewData = null : previewData = res01
   //console.log(3,previewData)
   previewData === null && res01 === undefined ? previewData = res02 :previewData = res01
   //console.log(4,previewData)
  let data 
  previewData !== null ? data = JSON.stringify(previewData) : data= null
  //console.log('data',data)
   
  


  // const found = (await data) === null ? false : true;

  // if (!found) {
  //   return {
  //     redirect: {
  //       destination: "/404",
  //       permanent: false,
  //     },
  //   };
  // }

  return {
    props: {
      data: data,
    },
  };
};
