//Fuente
import { Inter } from "next/font/google";
//Components
import Head from "next/head";
import ClientOnly from "@/components/ClientOnly/ClientOnly";
import Header from "@/components/Header/Header";
import Donativos from "@/components/Donativos/Donativos";
import Contact from "@/components/Contact/Contact";
import Footer from "@/components/Footer/Footer";
//Hooks
import useDevice from "@/hooks/useDevice";
//Models
import DeviceUnvailable from "@/components/DeviceUnvailable/DeviceUnvailable";

export default function Apadriname() {
  const { device } = useDevice();

    return (
      <>
        <Head>
          <title>Brigada Murci Adoptables</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/BrigadaMurciLogoV.png" />
        </Head>
        <ClientOnly>
          <DeviceUnvailable device={device}/>
          <Header device={device}/>
          <Donativos device={device} />
          <Contact device={device}/>
          <Footer device={device}/>
        </ClientOnly>
      </>
    );
}
