//Librerias
import React from "react";
//Components
import Head from "next/head";
import ClientOnly from "@/components/ClientOnly/ClientOnly";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
const donacion = () => {
  return (
    <>
      <Head>
        <title>Brigada Murci Adoptables</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BrigadaMurciLogoV.png" />
      </Head>
      <ClientOnly>
        <Header />
        <div>Aqui donaras money para que la GAbiis se apure y me pase el UXUI para que quede chida la pagina</div>
        <Footer />
      </ClientOnly>
    </>
  );
};

export default donacion;
