//Librerias
import React from "react";
//Components
import Head from "next/head";
import ClientOnly from "@/components/ClientOnly/ClientOnly";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Collection from "@/components/Colletction/Collection";
//DATABASE
import { gatosExample } from "../../database/examples/gatosExample";

const gatos = () => {
  return (
    <>
      <Head>
        <title>Brigada Murci Adoptables</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BrigadaMurciLogoV.png" />
      </Head>
      <ClientOnly>
        <Header />
        <Collection collection="gatos" data={gatosExample} />
        <Footer />
      </ClientOnly>
    </>
  );
};

export default gatos;
