//Fuente
import { Inter } from "next/font/google";
//Components
import Head from "next/head";
import Prueba from "@/components/Prueba/Prueba";
import ClientOnly from "@/components/ClientOnly/ClientOnly";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Brigada Murci</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BrigadaMurciLogo.png" />
      </Head>
      <ClientOnly>
        <Prueba />
      </ClientOnly>
    </>
  );
}
