//Fuente
import { Inter } from "next/font/google";
//Components
import Head from "next/head";
import ClientOnly from "@/components/ClientOnly/ClientOnly";
import Header from "@/components/Header/Header";
import Banner from "@/components/Banner/Banner";
import Footer from "@/components/Footer/Footer";
import BuscandoMejorAmigo from "@/components/BuscandoMejorAmigo/BuscandoMejorAmigo";
//Hooks
import useDevice from "@/hooks/useDevice";
//Models
import DeviceUnvailable from "@/components/DeviceUnvailable/DeviceUnvailable";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { device } = useDevice();

    return (
      <>
        <Head>
          <title>Brigada Murci Adoptables</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/BrigadaMurciLogoV.png" />
        </Head>
        <ClientOnly>
          <DeviceUnvailable device={device}/>
          <Header device={device}/>
          <Banner device={device}/>
          {/* <BuscandoMejorAmigo />
          <Footer /> */}
        </ClientOnly>
      </>
    );
}
