//Librerias
import React from "react";
//Components
import Head from "next/head";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import ClientOnly from "@/components/ClientOnly/ClientOnly";
import Collection from "@/components/Colletction/Collection";
//DATABASE
import { perrosExample } from "../../database/examples/perrosExample";

const perros = () => {
  return (
    <>
      <Head>
        <title>Brigada Murci Adoptables</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/BrigadaMurciLogoV.png" />
      </Head>
      <ClientOnly>
        <Header />
        <Collection collection="perros" data={perrosExample} />
        <Footer />
      </ClientOnly>
    </>
  );
};

export default perros;
